### ISSUE TITLE
Support open from different roots?

### ISSUE THREAD

**Issue by xaljer** [weirongxu/coc-explorer#198]
- open from working directory
- open from root directory of VSC repository
- open from directory which current file in

**Comment by weirongxu** [comment]
Can you explain your use case? why the root-uri option can't do it, or you just want to define some default root strategy

**Comment by Akin909** [comment]
I think this would be very useful from my perspective I guess you can achieve a similar thing by doing something like `execute 'CocCommand explorer ' . getcwd()` but I personally think it would be useful to allow the user to have more flexibility.

In my case I work in a v. large monorepo of 1500 directories and 10,000+ files I'm often only working on just one directory so having CocExplorer be in the monorepo root is not useful since theres a lot of noise so I usually open explorer then manually cd to the dir Im working in.

Another thing I often do is open files in different projects in different tabs, but in those cases the explorer root stays the same instead of following the project vcs root or my vim cwd

**Comment by xaljer** [comment]
@weirongxu , My use case is quite same as that of @Akin909 . In a large code base, people often want to explore some local directories instead of starting from project root. In project like AOSP, I open it from root which `.repo` exist. And a sub-module is often a git repository which indicate by `.git`. And sometimes I want to explore files around the current file.
I use fuzzy finder to 'open' files, and this kind of tools is used to 'explore' directory structure from any node of tree.

**Comment by johnpyp** [comment]
I solved my issue regarding this by using `:execute 'CocCommand' getcwd()`, but I agree it would be nice to have different modes of opening for working in monorepos.

**Comment by jrock2004** [comment]
Maybe there could be a setting that is a boolean. If it's true then when explorer opens it takes you to the directory that you are in. If its false it would take you to the root of the project

**Comment by Seybo** [comment]
@johnpyp @akinsho guys i'm probably missing something simple here but `execute 'CocCommand explorer ' . getcwd()` opens my home folder. Is it what it should open? I'm trying to open the parent folder of my currently opened buffer-file that is outside of any git repo

**Comment by akinsho** [comment]
@Seybo I use [vim-rooter](https://github.com/airblade/vim-rooter) to automatically set my `cwd` to my project root which is why that solution works for me

**Comment by xaljer** [comment]
> 
> 
> Maybe there could be a setting that is a boolean. If it's true then when explorer opens it takes you to the directory that you are in. If its false it would take you to the root of the project

@jrock2004 I don't think it's flexible enough. In a big project, sometimes I want to open in the git root, sometimes I want to open in the directory of current file.

**Comment by weirongxu** [comment]
https://github.com/weirongxu/coc-explorer#--root-strategies-root-strategies
