### ISSUE TITLE
Some icons are only partially rendered

### ISSUE THREAD

**Issue by shans10** [weirongxu/coc-explorer#200]
### Description of issue
I am using neovim v0.4.3-3 on Arch Linux.

With both vim devicons and Nerd Fonts installed some icons are not rendered properly specially the ones which are wider probably due to less character space assigned for icons. I only observed this issue with icons for C programs and header files for now.

I have tried both  `explorer.icon.enableVimDevicons": true` and `explorer.icon.enableNerdfont": true` in coc-settings.json and in both cases this issue was observed.

***Here's a screenshot of the issue:-***

![Screenshot_2020-06-02-46_245x333](https://user-images.githubusercontent.com/28944997/83485726-474d9200-a4c5-11ea-808a-94d63708fbe3.png)

***This is the explorer section of my coc config:-***
```"explorer.width": 31,
  "explorer.quitOnOpen": true,
  "explorer.icon.enableNerdfont": true,
  "explorer.previewAction.onHover": false,
  "explorer.icon.enableVimDevicons": false,
  "explorer.keyMappings": {
    "<cr>": ["expandable?", "expand", "open"],
    "v": "open:vsplit",
    "cd": "cd",
    "gp": "gotoParent",
    "gP": "preview:labeling"
  }
```

**Comment by weirongxu** [comment]
Should be the problem of your font or terminal

**Comment by shans10** [comment]
Thank you changing the font size fixed the issue!

**Comment by andys8** [comment]
I think this has to to do with "full width" / "double width" fonts and some terminals (e.g. st). Because it's working with nerd tree, there might be a way to improve this.

## Nerd Tree

![image](https://user-images.githubusercontent.com/13085980/93147380-501f4800-f6f1-11ea-9fe2-835e55b51389.png)

There are also options in that regard:
https://github.com/ryanoasis/vim-devicons/blob/695a918711630cd844988392af467d4e46de3de2/doc/webdevicons.txt#L603-L605

## coc-explorer

### with Nerd Font

![image](https://user-images.githubusercontent.com/13085980/93147414-65947200-f6f1-11ea-9ea5-c972aa69ef07.png)

### with Dev Icons

![image](https://user-images.githubusercontent.com/13085980/93147457-85c43100-f6f1-11ea-8fa1-0de20fbaad48.png)

**Comment by weirongxu** [comment]
@andys8 This question is related to `:highlight`. When `guifg` takes effect, will cause this. If you are using nvim, you can use `set notermguicolors` to disable `guibg`

**Comment by jsycdut** [comment]
guys, I got the same problem, fixed by using the font downloaded in https://github.com/ryanoasis/nerd-fonts/releases/tag/v2.1.0

by the way, I'm using arch + dwm + st + neovim, maybe the problem is platform irrelevant and can be fixed by using the right font
